services:
  - type: web
    name: websvc
    env:
      JWT_PRIVATE_KEY: ${{ env.ENV_JWT_PKEY }}
    buildCommand: docker build -t web-app .
    startCommand: docker run -p 5000:80 web-app
    healthCheckPath: /
    healthCheckPort: 5000
    healthCheckTimeoutSeconds: 10
    envVars:
      - key: ENV_JWT_PKEY
        fromServices:
          - type: web
            key: JWT_PRIVATE_KEY
  - name: db
    startCommand: docker run -e "SA_PASSWORD=${{ env.ENV_DB_PASSWORD }}" -e "ACCEPT_EULA=Y" -p 1433:1433 -d mcr.microsoft.com/mssql/server:2022-latest
    healthCheckPath: /
    healthCheckPort: 1433
    healthCheckTimeoutSeconds: 10
    envVars:
      - key: ENV_DB_PASSWORD
        fromServices:
          - type: db
            key: SA_PASSWORD